version: '3.8'

services:
  wiremock:
    image: wiremock/wiremock:2.35.0
    container_name: cbp-wiremock
    ports:
      - "8081:8080"
    volumes:
      - ./docker/wiremock/mappings:/home/wiremock/mappings:ro
      - ./docker/wiremock/__files:/home/wiremock/__files:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/__admin/mappings"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: cbp-app
    ports:
      - "8080:8080"
    environment:
      - EXTERNAL_API_BASE_URL=http://wiremock:8080
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      wiremock:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5

