name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: "java-ci-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    env:
      MAVEN_OPTS: "-Xmx2g -XX:+UseG1GC"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Make Maven wrapper executable
        run: chmod +x mvnw || true

      - name: Verify Maven and Java
        run: |
          java -version
          ./mvnw -v

      - name: Run tests
        run: |
          ./mvnw -B -V --no-transfer-progress test
        # If you prefer build and tests in one step use: ./mvnw -B -V --no-transfer-progress verify

      - name: Package
        run: |
          ./mvnw -B -V --no-transfer-progress -DskipTests=false package

      - name: Upload Surefire reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: target/surefire-reports

      - name: Upload built jar
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: built-jar
          path: target/*.jar

      # Optional: trigger additional workflows (deploy) here



